services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: emp_api
    depends_on:
      - db
    networks:
      - default
    ports:
      - 9000:9000
    env_file:
      - .env

  db:
    image: postgres
    container_name: emp_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: emp_celery
    networks:
      - default
    depends_on:
      - db
      - api
    env_file:
      - .env

volumes:
  db_data:

networks:
  default:
    driver: bridge
