services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: emp_api
    ports:
      - 9000:9000
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: emp_celery
    depends_on:
      - api
    env_file:
      - .env
